name: airdash
description: Share files anywhere
publish_to: 'none'

version: 2.0.145+145

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.9.14
  http: ^0.13.4
  file_picker: ^5.0.0
  path_provider: ^2.0.10
  share_plus: ^6.2.0
  shared_preferences: ^2.0.15
  receive_sharing_intent: ^1.4.5
  # Using fork to avoid avoid noisy print
  firedart: #^0.9.0+1
    git:
      url: https://github.com/erikhellq/firedart
      ref: patch-1
  url_launcher: ^6.1.2
  package_info_plus: ^3.0.1
  device_info_plus: ^8.0.0
  desktop_drop: ^0.3.3
  quick_look: ^0.0.4
  window_manager: ^0.2.5
  mime: ^1.0.2
  sentry_flutter: ^6.7.0
  grpc: ^3.0.2
  wakelock: ^0.6.1+2
  simple_peer: ^0.0.10
    #path: ./libs/simple_peer
  flutter_riverpod: ^1.0.4
  mixpanel_analytics: ^2.1.1
  dbus: ^0.7.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  dart_jsonwebtoken: ^2.4.1
  icons_launcher: ^2.0.6

  flutter_lints: ^2.0.1
  test: ^1.21.1
  msix: ^3.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: AirDash
  publisher_display_name: Flownio
  publisher: CN=74819260-D638-4972-AE3E-CA996FB6EF34
  identity_name: 24192Flownio.AirDash
  logo_path: logo.png
  capabilities: internetClient
  store: true

icons_launcher:
  image_path: 'assets/app_icon_rect.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/app_icon_round.png'
      adaptive_background_image: 'assets/app_icon_background.png'
      adaptive_foreground_image: 'assets/app_icon_foreground.png'
    ios:
      enable: true
    macos:
      enable: true
      image_path: 'assets/app_icon_round_with_padding.png'
    windows:
      enable: true
      image_path: 'assets/app_icon_round.png'
