name: airdash
base: core18
version: '2.0.142'
summary: Not used
description: Not used

grade: stable
confinement: strict

slots:
  dbus-airdash:
    interface: dbus
    bus: session
    name: io.flown.airdash

apps:
  airdash:
    command: airdash
    extensions: [flutter-stable]
    plugs:
      - network
      - audio-playback
      - audio-record
      - home
      - network-manager
      - personal-files
      - system-observe
      - screen-inhibit-control
      - screencast-legacy
      - pulseaudio
      - network-status
      - network-observe
      - network-bind
      - network-control
      - network-manager-observe
      - desktop
    slots:
      - dbus-airdash

parts:
  airdash-part:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
